### ISSUE TITLE
Set params

### ISSUE THREAD

**Issue by yashmulgaonkar** [IRNAS/max1720x#1]
Hi,
Thanks for a great library!

Do you have any plans for implementing functions to set battery parameters for the 17205?
eg. the FullCapRep register for battery capacity?

Thanks!

**Comment by SloMusti** [comment]
At the moment we have implemented features required for a project and have no immediate plan to write the complete support. Should we get a project to require this, we will add these features.

**Comment by yashmulgaonkar** [comment]
Fair enough. Thanks anyway...
